version: "3.8"

services:
  json-client:
    image: ${REPO}/grpc-json-client-sb
    ports:
      - "8080:8080"
    environment:
      - json.server.host=json-server

  json-server:
    image: ${REPO}/grpc-json-server-sb
    ports:
      - "8090:8090"

  grpc-client:
    image: ${REPO}/grpc-grpc-client-sb
    ports:
      - "8180:8180"
    environment:
      - grpc.server.host=grpc-intermediate
      - grpc.server.port=6564

  grpc-intermediate:
    image: ${REPO}/grpc-grpc-intermediate-sb
    ports:
      - "6564:6564"
    environment:
      - grpc.server.host=grpc-server
      - grpc.port=6564

  grpc-server:
    image: ${REPO}/grpc-grpc-server-sb
    ports:
      - "6565:6565"

  reference:
    image: ${REPO}/grpc-reference-sb
    ports:
      - "8280:8280"
