version: "2"

services:
  eureka:
    image: eureka
    ports:
      - "8761:8761"
    mem_limit: 700m

  #  admin:
#    image: admin
#    ports:
#      - "8380:8380"
#    environment:
#      - EUREKA_HOST=eureka

  json-client:
    image: json-client
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=eureka
      - logstash.host=elk
    mem_limit: 700m

  json-server:
    image: json-server
    ports:
      - "8090:8090"
    environment:
      - EUREKA_HOST=eureka
      - logstash.host=elk
    mem_limit: 700m

  grpc-client:
    image: grpc-client
    ports:
      - "8180:8180"
    environment:
      - EUREKA_HOST=eureka
      - logstash.host=elk
    mem_limit: 700m

  grpc-server:
    image: grpc-server
    ports:
      - "6565:6565"
    environment:
      - EUREKA_HOST=eureka
      - logstash.host=elk
    mem_limit: 700m

  reference:
    image: reference
    ports:
      - "8280:8280"
    environment:
      - EUREKA_HOST=eureka
      - logstash.host=elk
    mem_limit: 700m

#  elk:
#    image: local-elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"
#    mem_limit: 4g