spring:
  application:
    name: reference

server:
  port: 8280

eureka:
  instance:
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: 'http://${eureka.host:localhost}:${eureka.port:8761}/eureka/'