spring:
  application:
    name: admin

server:
  port: 8380

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: 'http://${eureka.host:localhost}:${eureka.port:8761}/eureka/'